### REQUIRED

namespace: nginxinc
name: nginx_controller
version: 3.10.0
readme: README.md
authors:
- brianehlert
dependencies: {}
license:
- Apache-2.0
tags:
- nginx
- controller
- nginxplus
- plus
- tools
- infrastructure
- cloud
- linux
- security
- monitoring

description: Supporting NGINX Controller 3.x in your pipelines.
repository: https://github.com/nginxinc/ansible-collection-nginx_controller
documentation: https://docs.nginx.com/nginx-controller/
issues: https://github.com/nginxinc/ansible-collection-nginx_controller/issues
